// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4ReZHlgwBi21r4ZzpFy2Zhjv1BzDTxE',
    appId: '1:572488733255:web:1d65d52d5b7b83c37dd762',
    messagingSenderId: '572488733255',
    projectId: 'legacy-b671e',
    authDomain: 'legacy-b671e.firebaseapp.com',
    storageBucket: 'legacy-b671e.appspot.com',
    measurementId: 'G-G4048TRP1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiAfG9h0fE_BVRMj-HLF5qOCp5rUt_zZU',
    appId: '1:572488733255:android:4141a3c2ac6283be7dd762',
    messagingSenderId: '572488733255',
    projectId: 'legacy-b671e',
    storageBucket: 'legacy-b671e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNhy_YASYwmrQRpX29L_gYNhymJXS9GbE',
    appId: '1:572488733255:ios:53603dcccb0a27197dd762',
    messagingSenderId: '572488733255',
    projectId: 'legacy-b671e',
    storageBucket: 'legacy-b671e.appspot.com',
    iosBundleId: 'com.example.tictokClone',
  );
}
